server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dilshika/microservice-config
          search-paths:
            - 'service-config/*service'

