management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee?createDatabaseIfNotExist=true
    username: root
    password: rootFor1917@
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update