spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?createDatabaseIfNotExist=true
    username: root
    password: rootFor1917@
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: profile
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
  client:
    client-id: mobile
    client-secret: pin